# Real R execution and numerical parity, without touching the user's datasets.
lib <- normalizePath(commandArgs(trailingOnly = TRUE)[[1]])
.libPaths(c(lib, .libPaths()))
suppressPackageStartupMessages(library(mrmhub, lib.loc = lib))
root <- normalizePath(".")
engine <- tempfile("quant-legacy-"); dir.create(engine)
for (name in c("runner.R", "catalog.R", "legacy.R")) file.copy(file.path(root, "integrator_w_gui/gui/src-tauri/quant", name), engine)
project <- file.path(engine, "dataset"); dir.create(project)
file.copy(file.path(root, "inst/extdata/MRMhub_demo.tsv"), file.path(project, "input.tsv"))
counter <- 0L
run <- function(code, parent = "", success = TRUE) {
  counter <<- counter + 1L
  work <- file.path(engine, paste0("job-", counter)); dir.create(work)
  jsonlite::write_json(list(action = "legacy", checkpoint = parent, code = code, project = project, progressToken = paste0("test-", counter)), file.path(work, "request.json"), auto_unbox = TRUE)
  status <- system2(file.path(R.home("bin"), "Rscript"), c("--vanilla", shQuote(file.path(engine, "runner.R")), "legacy", shQuote(engine), shQuote(work), shQuote(lib)), stdout = file.path(work, "run.log"), stderr = file.path(work, "run.log"))
  if (success && status != 0) stop(paste(readLines(file.path(work, "run.log")), collapse = "\n"))
  if (!success && status == 0) stop("Expected failure")
  list(work = work, checkpoint = file.path(work, "workspace.rds"), result = if (status == 0) jsonlite::read_json(file.path(work, "result.json"), simplifyVector = TRUE) else NULL)
}
first <- run('library(mrmhub)\nlibrary(dplyr)\nx <- 41\nadd_x <- function(y) x + y\nset.seed(321)\nprint("first block")')
stopifnot(file.exists(first$checkpoint), length(first$result$tables) == 0)
progress_records <- function(work) {
  lines <- readLines(file.path(work, "run.log"), warn = FALSE)
  prefix <- "__MRMHUB_QUANT_PROGRESS__"
  lapply(substring(lines[startsWith(lines, prefix)], nchar(prefix) + 1L), jsonlite::fromJSON)
}
progress <- progress_records(first$work)
percentages <- vapply(progress, `[[`, numeric(1), "percent")
stopifnot(percentages[[1]] == 0, tail(percentages, 1) == 100, all(diff(percentages) >= 0), length(progress) == 9L)
stopifnot(all(vapply(progress, function(p) p$token == "test-1", logical(1))))
cat("PASS actual statement/session progress with run correlation\n")
second <- run('stopifnot(x == 41, add_x(1) == 42)\nr <- runif(3)\nx <- x + 1\nprint(tibble(value = x) |> mutate(value = value + 1))\nmexp <- import_data_mrmhub(MRMhubExperiment(title = "Legacy"), path = "input.tsv", import_metadata = TRUE)', first$checkpoint)
session <- readRDS(second$checkpoint)
set.seed(321); stopifnot(identical(session$workspace$r, runif(3)), session$workspace$x == 42)
setwd(project)
direct <- import_data_mrmhub(MRMhubExperiment(title = "Legacy"), path = "input.tsv", import_metadata = TRUE)
setwd(root)
stopifnot(identical(readRDS(second$checkpoint)$workspace$mexp, direct))
stopifnot(!file.exists(file.path(second$work, "experiment.rds")))
cat("PASS session objects, closures, packages, RNG, relative paths, exact import parity\n")
third <- run('mexp <- set_intensity_var(mexp, variable_name = "area")\nplot_runsequence(mexp)\nplot(1:3)\nView(head(mexp@dataset))\nwrite.csv(data.frame(value = x), file.path(output_dir, "custom.csv"))', second$checkpoint)
expected <- set_intensity_var(direct, variable_name = "area")
stopifnot(identical(readRDS(third$checkpoint)$workspace$mexp, expected))
stopifnot(!file.exists(file.path(third$work, "experiment.rds")))
table_work <- file.path(engine, "table-preview"); dir.create(table_work)
jsonlite::write_json(list(action="table", checkpoint=third$checkpoint, legacyTable=TRUE, table="dataset", offset=0, limit=5), file.path(table_work,"request.json"), auto_unbox=TRUE)
table_status <- system2(file.path(R.home("bin"), "Rscript"), c("--vanilla", shQuote(file.path(engine,"runner.R")), "run", shQuote(engine), shQuote(table_work), shQuote(lib)), stdout=file.path(table_work,"run.log"), stderr=file.path(table_work,"run.log"))
stopifnot(table_status == 0)
preview <- jsonlite::read_json(file.path(table_work,"result.json"), simplifyVector=TRUE)
stopifnot(identical(preview$columns,names(expected@dataset)), preview$total == nrow(expected@dataset), nrow(preview$rows) == 5)
cat("PASS table previews use the single workspace snapshot without a duplicate experiment file\n")
stopifnot(sum(third$result$artifacts$kind == "image") >= 2L, file.exists(file.path(third$work, "custom.csv")))
for (name in third$result$artifacts$name[third$result$artifacts$kind == "image"]) {
  header <- readBin(file.path(third$work, name), "raw", n = 24)
  dimensions <- readBin(header[17:24], "integer", n = 2, size = 4, endian = "big")
  stopifnot(all(abs(dimensions - c(1684, 1190) / 144 * 300) < 2))
}
cat("PASS original QUANT calls, ggplot/base plots, View and explicit exports\n")
hash <- tools::md5sum(third$checkpoint)
old_graphs <- file.path(third$work, third$result$artifacts$name[third$result$artifacts$kind == "image"])
graph_hashes <- tools::md5sum(old_graphs)
failed <- run('x <- 100\nstop("intentional failure")', third$checkpoint, success = FALSE)
stopifnot(!file.exists(failed$checkpoint), identical(hash, tools::md5sum(third$checkpoint)))
stopifnot(all(vapply(progress_records(failed$work), `[[`, numeric(1), "percent") < 100))
later <- run('stopifnot(x == 42)\nprint(add_x(2))', third$checkpoint)
stopifnot(identical(graph_hashes, tools::md5sum(old_graphs)), !any(later$result$artifacts$kind == "image"))
cat("PASS earlier graphs stay unchanged, with no copied images in later checkpoints\n")
run('x <- ', third$checkpoint, success = FALSE)
fresh <- run('stopifnot(!exists("x"))\nprint("fresh session")')
stopifnot(length(fresh$result$objects) == 0)
cat("PASS runtime/syntax error isolation and fresh-session isolation\n")
single <- run('one_object <- 1')
stopifnot(is.list(jsonlite::read_json(file.path(single$work, "result.json"))$objects))
cat("PASS stable JSON arrays with one saved object\n")
copied <- run('print(mexp@dataset)\n# A tibble: 250,997 × 21\n   analysis_order analysis_id\n            <int> <chr>\n 1              1 Longit_BLANK', second$checkpoint, success = FALSE)
stopifnot(any(grepl("unrecognized printed table output", readLines(file.path(copied$work, "error.txt")), fixed = TRUE)))
cleaned <- run('print(mexp@dataset)\n# A tibble: 250,997 × 21\n#    analysis_order analysis_id\n#             <int> <chr>\n#  1              1 Longit_BLANK', second$checkpoint)
stopifnot(identical(readRDS(cleaned$checkpoint)$workspace$mexp, direct))
missing <- run('print(mexp@dataset)', success = FALSE)
stopifnot(any(grepl("Run step 2 successfully", readLines(file.path(missing$work, "error.txt")), fixed = TRUE)))
bad_path <- run('mexp <- import_data_mrmhub(MRMhubExperiment(), path = "./datasets/sPerfect_MRMhub.tsv")', success = FALSE)
stopifnot(any(grepl("Insert import for this dataset", readLines(file.path(bad_path$work, "error.txt")), fixed = TRUE)))
cat("PASS reproduced tutorial paste failure, cleaned output parity, missing import/path guidance\n")
styled <- run('mrmhub_set_plot_defaults(font_base_size = 9, point_size = 2)', second$checkpoint)
style_restored <- run('stopifnot(mrmhub_get_plot_defaults()$font_base_size == 9, mrmhub_get_plot_defaults()$point_size == 2)\nmrmhub_reset_plot_defaults()', styled$checkpoint)
invisible(run('stopifnot(length(mrmhub_get_plot_defaults()) == 0)', style_restored$checkpoint))
invisible(run('mexp <- data_load_example()'))
cat("PASS new plot defaults survive blocks/reset and old bundled objects remain inspectable\n")
cat("All Legacy integration tests passed. Artifacts:", engine, "\n")
